### ISSUE TITLE
Suggestion: Default button URL should be Theme URI

### ISSUE THREAD

**Issue by carolinan** [WPTRT/customize-section-button#1]
Not an issue per see, but perhaps the default button URL should be the theme URI, if one exists, and if that does not exist, use Author URI, if it i exists.

**Comment by carolinan** [comment]
Ignore me. It is only the example in the readme that has a hardcoded link =)

**Comment by justintadlock** [comment]
I'm going to reopen.  Currently, yes, we fall back to the Theme URI.  However, falling back further to the Author URI if the Theme URI doesn't exist would be even better.
