### ISSUE TITLE
Class not Found Error

### ISSUE THREAD

**Issue by nicoandrade** [WPTRT/customize-section-button#6]
I'm always getting this error:
```php
Fatal error: Uncaught Error: Class 'WPTRT\Customize\Section\Button' not found in...
```

autoload.php is working fine with other Classes and I'm using the default code from the example:
```php
use WPTRT\Customize\Section\Button;

add_action( 'customize_register', function( $manager ) {

	$manager->register_section_type( Button::class );

	$manager->add_section(
		new Button( $manager, 'themeslug_pro', [
			'title'       => __( 'ThemeName Pro', 'themeslug' ),
			'button_text' => __( 'Go Pro',        'themeslug' ),
			'button_url'  => 'http://example.com'
		] )
	);

} );
```
The strange thing is that only this Button Class is having problems, not other ones.

**Comment by justintadlock** [comment]
Yeah, I know why.  I'll have a fix up shortly.

**Comment by justintadlock** [comment]
Corrected in https://github.com/WPTRT/customize-section-button/commit/64d71caf86c853d03231ac642b4655af02f1500d

I've bumped the version to 1.0.1, so you should just be able to pull in the latest changes.
